add test for task of adding event
itmo-events-app/event-app pull request #29
Opened 2024-04-01 14:09 UTC by LiaoYihong-1

2024-04-01 19:50 UTC, IP-13 commented
|Overall Project|74.13%|:green_apple:|
|:-|:-|:-:|

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/2032e9921a08ce53b7ed1b119289cb5bf88dd128/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|

2024-04-02 16:59 UTC, IP-13 commented
|Overall Project|73.65%|:green_apple:|
|:-|:-|:-:|

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/702f42c268d3aabaa5da7fb8a1b3ba1f2fc733ce/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|

2024-04-02 21:09 UTC, omgronny commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +        String eventJson = "{" +
Можно сделать multiline строку через """, и тогда во-первых, не нужны будут плюсы, а во-вторых, не нужно будет экранирование

2024-04-02 21:10 UTC, omgronny commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +                        post("/api/events/activity")
addActivity тут будет

2024-04-03 09:03 UTC, LiaoYihong-1 commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +                        post("/api/events/activity")
В url обычно не пишем add. Post уже значит созданиею.

2024-04-03 09:03 UTC, LiaoYihong-1 commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +        String eventJson = "{" +
Перепишу все. Там сейчас добавляю работу с картинку.

2024-04-03 11:04 UTC, IP-13 commented
|Overall Project|78.67% **`-1.61%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|91.12%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/cd219649a4b237e45c447f1d4bc0e183254a0e09/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[MinioService.java](https://github.com/itmo-events-app/event-app/blob/cd219649a4b237e45c447f1d4bc0e183254a0e09/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fminio%2FMinioService.java)|85.19% **`-7.94%`**|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/cd219649a4b237e45c447f1d4bc0e183254a0e09/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|81.44%|:green_apple:|

2024-04-03 18:11 UTC, omgronny requested changes

2024-04-03 18:11 UTC, omgronny commented on src/main/java/org/itmo/eventapp/main/model/dto/request/EventRequest.java
> +        @NotNull(message = "Поле parent не может быть null при создании активностей!")
Подожди, мы же при update event'а используем EventRequest. Значит тут вполне может быть null

2024-04-03 18:42 UTC, LiaoYihong-1 commented on src/main/java/org/itmo/eventapp/main/model/dto/request/EventRequest.java
> +        @NotNull(message = "Поле parent не может быть null при создании активностей!")
Я тоже про это задумываюсь. Потому что если мы поставим null для активности. То активность будет переобразована в мероприятие. Не знаю логично ли это.

2024-04-03 18:45 UTC, LiaoYihong-1 commented on src/main/java/org/itmo/eventapp/main/model/dto/request/EventRequest.java
> +        @NotNull(message = "Поле parent не может быть null при создании активностей!")
Исправлю

2024-04-03 19:01 UTC, thermvs commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
>      public void setup() {
Вместо функции setup() с аннотацией @beforeeach теперь приватная, посмотри в main

2024-04-03 19:17 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/model/dto/request/EventRequest.java
> +        @NotNull(message = "Поле parent не может быть null при создании активностей!")
Но давай в этом пул реквесте удалим эту аннотацию, если что в будущем добавим новую ДТО и там валидацию эту добавим

2024-04-03 19:33 UTC, IP-13 commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +        assertThat(isBucketExists).isTrue();
За assertJ лайк

2024-04-03 19:33 UTC, IP-13 commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +        boolean isImageExists = isImageExist("3.jpeg");
Еще бы добавить провеку, что event добавился в базу данных
Через репозиторий просто посмотреть

2024-04-03 19:35 UTC, IP-13 commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
>      public void setup() {
Заребейсись в main
Плохо заполнять данными в @BeforeEach, потому что тесты из-за этого начинают зависеть друг от друга

2024-04-03 19:42 UTC, LiaoYihong-1 commented on src/test/java/org/itmo/eventApp/main/controller/EventControllerTest.java
> +        boolean isImageExists = isImageExist("3.jpeg");
Это не база данных. Здесь minio

2024-04-03 21:07 UTC, IP-13 commented
|Overall Project|66.71% **`-0.88%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|91.98%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/87853fb1606de2351e0cc94b9e063ebee8ee3283/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/87853fb1606de2351e0cc94b9e063ebee8ee3283/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.26%|:green_apple:|
|[MinioService.java](https://github.com/itmo-events-app/event-app/blob/87853fb1606de2351e0cc94b9e063ebee8ee3283/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fminio%2FMinioService.java)|85.19% **`-7.94%`**|:green_apple:|

2024-04-03 21:13 UTC, thermvs approved these changes

2024-04-04 10:12 UTC, IP-13 approved these changes

2024-04-04 18:48 UTC, IP-13 commented
|Overall Project|48.17% **`-0.58%`**|:x:|
|:-|:-|:-:|
|Files changed|92.23%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EventController.java](https://github.com/itmo-events-app/event-app/blob/f3734c2002c9e5973c897bf26b73bd94ba3e3cb9/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FEventController.java)|100%|:green_apple:|
|[EventService.java](https://github.com/itmo-events-app/event-app/blob/f3734c2002c9e5973c897bf26b73bd94ba3e3cb9/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventService.java)|95.25%|:green_apple:|
|[MinioService.java](https://github.com/itmo-events-app/event-app/blob/f3734c2002c9e5973c897bf26b73bd94ba3e3cb9/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fminio%2FMinioService.java)|85.19% **`-7.94%`**|:green_apple:|

2024-04-04 18:50 UTC, merged