Basic roles functionality
itmo-events-app/event-app pull request #30
Opened 2024-04-02 10:00 UTC by rimnvd

2024-04-02 10:59 UTC, IP-13 commented
|Overall Project|29.25% **`-52.96%`**|:x:|
|:-|:-|:-:|
|Files changed|5.78%|:x:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[CommonControllerAdvice.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexceptionhandling%2FCommonControllerAdvice.java)|20.51% **`-61.54%`**|:x:|
|[UserService.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FUserService.java)|15.79% **`-84.21%`**|:x:|
|[PrivilegeService.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPrivilegeService.java)|11.11% **`-88.89%`**|:x:|
|[RoleController.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FRoleController.java)|7.84% **`-92.16%`**|:x:|
|[EventRoleService.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventRoleService.java)|7.5% **`-92.5%`**|:x:|
|[RoleService.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FRoleService.java)|3.02% **`-96.98%`**|:x:|
|[NotAllowedException.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FNotAllowedException.java)|0%|:x:|
|[IncorrectRoleTypeException.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FIncorrectRoleTypeException.java)|0%|:x:|
|[NotFoundException.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FNotFoundException.java)|0%|:x:|
|[NotUniqueException.java](https://github.com/itmo-events-app/event-app/blob/b1cb8a875ce71e7bd15d93e3275a7e6e545f5f5f/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FNotUniqueException.java)|0%|:x:|

2024-04-02 12:10 UTC, omgronny requested changes

2024-04-02 12:10 UTC, omgronny commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
А зачем эти два метода если есть третий внизу?

2024-04-02 12:13 UTC, rimnvd commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
Потому что **назначение роли помощника**, **назначение роли организатора** и **назначение организационной роли** - это отдельные привилегии

2024-04-02 12:34 UTC, IP-13 commented
|Overall Project|29.25% **`-52.96%`**|:x:|
|:-|:-|:-:|
|Files changed|5.78%|:x:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[CommonControllerAdvice.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexceptionhandling%2FCommonControllerAdvice.java)|20.51% **`-61.54%`**|:x:|
|[UserService.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FUserService.java)|15.79% **`-84.21%`**|:x:|
|[PrivilegeService.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPrivilegeService.java)|11.11% **`-88.89%`**|:x:|
|[RoleController.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FRoleController.java)|7.84% **`-92.16%`**|:x:|
|[EventRoleService.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventRoleService.java)|7.5% **`-92.5%`**|:x:|
|[RoleService.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FRoleService.java)|3.02% **`-96.98%`**|:x:|
|[NotAllowedException.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FNotAllowedException.java)|0%|:x:|
|[IncorrectRoleTypeException.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FIncorrectRoleTypeException.java)|0%|:x:|
|[NotFoundException.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FNotFoundException.java)|0%|:x:|
|[NotUniqueException.java](https://github.com/itmo-events-app/event-app/blob/93ab1fdfca2441cc8e78e36938ac90e9da268fee/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexception%2FNotUniqueException.java)|0%|:x:|

2024-04-02 12:45 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<List<RoleResponse>> searchByName(@RequestParam String name) {
Эта штука странно выглядит. Ищем роли по названию, название одно, а возващаем лист. Это типо админ будет искать роль по названию?
Комментарий бы добавить

2024-04-02 12:45 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok(roleService.createRole(roleRequest));
На создание ресурса 201 статус

2024-04-02 12:53 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
Если не возвращается энтити надо статус 204, а return type ResponseEntity<Void>
https://datatracker.ietf.org/doc/html/rfc2616#section-9.7

2024-04-02 12:56 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
Тут тоже бы привилегии указать над методами

2024-04-02 13:09 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +            @Min(3) @RequestBody Integer roleId) {
Мессаджы лучше прописывать во всех аннотациях валидации
Тем более тут костыль такой пока, отсылающему непонятно будет почему roleId не может быть 1 или 2

2024-04-02 13:10 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    @PostMapping("/organizer/{userId}/{eventId}")
Тут put. Не происходит создания нового ресурса

2024-04-02 13:11 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
А что тут возвращается?
ResponseEntity<Integer> возвращаемый тип

2024-04-02 13:12 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
Может void?

2024-04-02 13:12 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
Или даже лучше ResponseEntitiy< Void>

2024-04-02 13:13 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<Integer> assignAssistantRole(
Все тоже самое, что и к assignOrganizationalRole

2024-04-02 13:15 UTC, rimnvd commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    @PostMapping("/organizer/{userId}/{eventId}")
Если у пользователя не было роли в мероприятии, то создается новая запись в event_role

2024-04-02 13:17 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
У нас и на это разные привилегии, серьезно. Ну и ... ладно

2024-04-02 13:18 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    @DeleteMapping("/assistant/{userId}/{eventId}")
Тут put?

2024-04-02 13:20 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    @DeleteMapping("/organizer/{userId}/{eventId}")
Put

2024-04-02 13:20 UTC, rimnvd commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    @DeleteMapping("/organizer/{userId}/{eventId}")
Почему put, если мы запись из бд удаляется?

2024-04-02 13:21 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
Непонятно, что возвращаем

2024-04-02 13:21 UTC, rimnvd commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    @DeleteMapping("/assistant/{userId}/{eventId}")
Запись из бд удаляется

2024-04-02 13:22 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Лучше использовать ResponseStatusException

2024-04-02 13:23 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/exception/NotAllowedException.java
> +public class NotAllowedException extends RuntimeException {
Лучше использовать ResponseStatusException

2024-04-02 13:33 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/model/entity/Role.java
> +    public Role(RoleRequest roleRequest) {
Может это лучше в маппер вынести?

2024-04-02 13:35 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/repository/PrivilegeRepository.java
> +    List<PrivilegeResponse> findAllByType(PrivilegeType type);
А как он тут в eventResponse сразу превращается?

2024-04-02 13:36 UTC, rimnvd commented on src/main/java/org/itmo/eventapp/main/repository/PrivilegeRepository.java
> +    List<PrivilegeResponse> findAllByType(PrivilegeType type);
spring умный

2024-04-02 13:37 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/UserService.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Пользователь с id %d не существует", id)));
ResponseStatusException(HttpStatus.NOT_FOUND, "your message here")

2024-04-02 13:45 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/EventRoleService.java
> +                if (organizersInEvent.size() == 1)
А зачем тут эта проверка?
Мы же не забираем роль, а назначаем

2024-04-02 13:47 UTC, rimnvd commented on src/main/java/org/itmo/eventapp/main/service/EventRoleService.java
> +                if (organizersInEvent.size() == 1)
Мы вчера решили, что у пользователя может быть только одна роль в мероприятии, если оргу пытаться назначить что-то другое, а он всего один, то оргов не останется

2024-04-02 13:52 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/PrivilegeService.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Привилегия с id %d не существует", id)));
ResponseStatusException

2024-04-02 13:53 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/PrivilegeService.java
> +    public List<PrivilegeResponse> convertToDto(Collection<Privilege> privileges) {
Такие штуки лучше в мапперы выносить, ну ладно

2024-04-02 13:54 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/PrivilegeService.java
> +    public List<PrivilegeResponse> convertToDto(Collection<Privilege> privileges) {
ConvertToResponse лучше

2024-04-02 13:54 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<List<RoleResponse>> searchByName(@RequestParam String name) {
Там же еще кстати проверка при добавлении роли, чтобы имя уникальное

2024-04-02 13:56 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +        var role = roleRepository.findByName(roleRequest.name());
а может тут сразу exception бросать, если роли нет?

2024-04-02 13:58 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Роль с id %d не существует", id)));
ResponseStatusException

2024-04-02 14:11 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +        if (role.getType().equals(RoleType.SYSTEM)) {
Проверка на  то, что это администратор или читатель только на уровне контроллера, я так понимаю?
Может лучше здесь создать список ролей, которые нельзя удалять и проверять не содержит ли он переданную роль? Так понятнее и безопаснее

2024-04-02 14:13 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +        role.setPrivileges(null);
А EventRole тут каскадно удаляются?

2024-04-02 14:14 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +    public RoleResponse findById(Integer id) {
Из сервисов лучше не возвращать DTO, потому что сервисы используются в других сервисах и может получиться ситуация, что в другом сервисе нужна энтити (а так почти всегда и бывает), а возвращается dto

2024-04-02 14:15 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +    public RoleResponse findById(Integer id) {
Это много где, везде не буду писать

2024-04-02 14:15 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Роль с id %d не существует", id)));
ResponseStatusException

2024-04-02 14:18 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Роль с именем %s не существует", name)));
ResponseStatusException

2024-04-02 15:54 UTC, omgronny commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
Так давайте сделаем один метод, а внутри в зависимости от значения проверим нужную привилегию? Это от кучи дублирования нас избавит

2024-04-02 17:58 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<Integer> deleteRole(@Min(5) @PathVariable Integer id) {
поменяла

2024-04-02 17:58 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<Integer> deleteRole(@Min(5) @PathVariable Integer id) {
поменяла

2024-04-02 18:03 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
исправила

2024-04-02 18:06 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +public class RoleController {
добавила

2024-04-02 18:10 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +            @Min(3) @RequestBody Integer roleId) {
исправила

2024-04-02 18:12 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +        return ResponseEntity.ok().build();
исправила

2024-04-02 18:13 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<Integer> assignSystemRole(
исправила

2024-04-02 18:31 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/service/RoleService.java
> +        var role = roleRepository.findByName(roleRequest.name());
исправила

2024-04-02 19:00 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/model/entity/Role.java
> +    @NotBlank(message = "Название роли обязательно")
сделала все под jakarta

2024-04-02 19:02 UTC, IP-13 commented
|Overall Project|32.45% **`-50.33%`**|:x:|
|:-|:-|:-:|
|Files changed|7.81%|:x:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[CommonControllerAdvice.java](https://github.com/itmo-events-app/event-app/blob/4125c12cb55fa469dc4d14b936ce3b37c9e24f82/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fexceptionhandling%2FCommonControllerAdvice.java)|53.33%|:green_apple:|
|[UserService.java](https://github.com/itmo-events-app/event-app/blob/4125c12cb55fa469dc4d14b936ce3b37c9e24f82/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FUserService.java)|15.38% **`-84.62%`**|:x:|
|[PrivilegeService.java](https://github.com/itmo-events-app/event-app/blob/4125c12cb55fa469dc4d14b936ce3b37c9e24f82/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FPrivilegeService.java)|10.91% **`-89.09%`**|:x:|
|[RoleController.java](https://github.com/itmo-events-app/event-app/blob/4125c12cb55fa469dc4d14b936ce3b37c9e24f82/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fcontroller%2FRoleController.java)|7.41% **`-92.59%`**|:x:|
|[EventRoleService.java](https://github.com/itmo-events-app/event-app/blob/4125c12cb55fa469dc4d14b936ce3b37c9e24f82/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FEventRoleService.java)|7.32% **`-92.68%`**|:x:|
|[RoleService.java](https://github.com/itmo-events-app/event-app/blob/4125c12cb55fa469dc4d14b936ce3b37c9e24f82/src%2Fmain%2Fjava%2Forg%2Fitmo%2Feventapp%2Fmain%2Fservice%2FRoleService.java)|7.16% **`-92.84%`**|:x:|

2024-04-03 20:34 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
добавим со спрингом

2024-04-03 20:35 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
напишем с секьюрити уже

2024-04-03 20:36 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    public ResponseEntity<List<RoleResponse>> searchByName(@RequestParam String name) {
я думаю это для того, чтобы если похожие названия, то выдавало все их, а не по полному совпадению

2024-04-03 20:37 UTC, IP-13 commented on src/main/java/org/itmo/eventapp/main/repository/PrivilegeRepository.java
> +    List<PrivilegeResponse> findAllByType(PrivilegeType type);
Ну в любом случае, репозиторий должен работать с entity, надо поменять

2024-04-03 20:43 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/model/entity/Role.java
> +    public Role(RoleRequest roleRequest) {
сделала

2024-04-03 20:49 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/service/PrivilegeService.java
> +    public List<PrivilegeResponse> convertToDto(Collection<Privilege> privileges) {
вынесла

2024-04-03 21:03 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/repository/PrivilegeRepository.java
> +    List<PrivilegeResponse> findAllByType(PrivilegeType type);
fix

2024-04-03 21:05 UTC, anamrzv commented on src/main/java/org/itmo/eventapp/main/controller/RoleController.java
> +    }
позже решим как лучше

2024-04-03 21:06 UTC, anamrzv approved these changes

2024-04-03 21:37 UTC, merged